const PRODUCTION_HOSTNAME = 'dlevs.com';

module.exports = {
	SINGLE_PIXEL_TRANSPARENT: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
	PRODUCTION_HOSTNAME,
	PRODUCTION_ORIGIN: `https://${PRODUCTION_HOSTNAME}`
};
